import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import styles from './page.module.css';
import { Header } from '@/components/Header/Header';
import { Sidebar } from '@/components/Sidebar/Sidebar';
import { Footer } from '@/components/Footer/Footer';
import { firstLevelMenu } from '@/helpers/helpers';
import { getMenu } from '@/api/getMenu';

// const inter = Inter({ subsets: ['latin'] });

const notoSans = Noto_Sans({
	subsets: ['latin'],
	weight: ['300', '400', '500', '700'],
	style: 'normal'
});

export const metadata: Metadata = {
	title: 'My TOP',
	description: 'Generated by create next app'
};

export default async function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	const menu = await Promise.all(firstLevelMenu.map(({ id }) => getMenu(id)));

	return (
		<html lang="en">
			<body className={notoSans.className}>
				<div className={styles.wrapper}>
					<Header className={styles.header} menu={menu} />

					<Sidebar className={styles.sidebar} menu={menu} />
					<div className={styles.body}>{children}</div>

					<Footer className={styles.footer} />
				</div>
			</body>
		</html>
	);
}
